package Forms;

import Operaciones.ConexionMongoDB;
import Operaciones.Verifica;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 * @author ROQUEARMANDORAMIREZP
 */
public class FrmSeguimiento extends javax.swing.JInternalFrame {

    String StrCodFila;
    ConexionMongoDB conexion = new ConexionMongoDB();

    /**
     * Creates new form FrmAbout
     */
    public FrmSeguimiento(String IdFicha) {
        initComponents();
        this.StrCodFila = IdFicha;
        //System.out.println("\t\t EL cod ES: " + StrIdFicha);
        CargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableVisita = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jComboEst = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtFec = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTexComen = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLblEst = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Seguimiento");

        JTableVisita= new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        JTableVisita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTableVisita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(JTableVisita);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Visita"));

        jComboEst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desinteresado", "Fallecido", "Incierto", "Trabajable", "Traslado" }));
        jComboEst.setSelectedIndex(-1);

        jLabel1.setText("Estado:");

        jLabel2.setText("Fecha Visita:");

        TxtFec.setToolTipText("Ingrese Fecha del Formato: (AAAA-MM-DD)");
        TxtFec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtFecKeyTyped(evt);
            }
        });

        jLabel3.setText("Comentarios:");

        jTexComen.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jButton2.setText("Agregar Nuevo Seguimiento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jComboEst, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TxtFec, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTexComen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboEst, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtFec))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTexComen)))
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtFec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexComen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jLblEst.setText("acm1pt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblEst)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLblEst)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFecKeyTyped
        if (TxtFec.getText().length() >= 10) {
            evt.consume(); // impide que ingresen más de 30 caracteres
        }
    }//GEN-LAST:event_TxtFecKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*1-Desinteresado
        2-Fallecido
        3-Incierto
        4-Trabajable
        5-Traslado */
        if (!Validacion()) {
            return;
        }
        //Document visita = new Document("fev", TxtFec.getText()).append("com", jTexComen.getText());
        //if (conexion.AnexaDocEnDoc(StrCodFila, visita)) {// si al guardar todo sale bien
        
        conexion.NuevoSeguimiento(StrCodFila, TxtFec.getText(), jTexComen.getText(), String.valueOf(jComboEst.getSelectedIndex() + 1));
        JOptionPane.showMessageDialog(null, "Exito Al Agregar Seguimiento", "Exito", JOptionPane.INFORMATION_MESSAGE);
        CargarDatos();
        jTexComen.setText("");
        TxtFec.setText("");
        jComboEst.setSelectedIndex(-1);

    }//GEN-LAST:event_jButton2ActionPerformed

    private Boolean Validacion() {
        Verifica validacion = new Verifica();
        Boolean Rpta = true;
        if (jComboEst.getSelectedIndex() < 0) {
            Rpta = false;
            JOptionPane.showMessageDialog(null, "Seleccione Sexo", "Notificación:", JOptionPane.WARNING_MESSAGE);
            jComboEst.requestFocus();
        } else if (!validacion.EsFecha(TxtFec.getText())) {
            Rpta = false;
            JOptionPane.showMessageDialog(null, "Corrija Fecha", "Notificación:", JOptionPane.WARNING_MESSAGE);
            TxtFec.requestFocus();
        } else if (jTexComen.getText().length() < 1) {
            Rpta = false;
            JOptionPane.showMessageDialog(null, "Ingrese comentario sobre visita", "Notificación:", JOptionPane.WARNING_MESSAGE);
            jTexComen.requestFocus();
        }
        return Rpta;
    }

    private void CargarDatos() {
        Document archivo = conexion.obtenerArchivoPorId(StrCodFila);
        if (archivo != null) {//si lo encuentra
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Fecha Visita");
            modelo.addColumn("Comentario");

            String StrNom = archivo.getString("nom");
            String StrApe = archivo.getString("ape");
            String StrEst = archivo.getString("est");
            this.setTitle("Seguimiento de " + StrNom + " " + StrApe);
            if (StrEst != null) {
                jLblEst.setText("Estado Actual: " + jComboEst.getItemAt(Integer.parseInt(StrEst) - 1));
            } else {
                jLblEst.setText("Estado Actual: *AÚN NO DEFINIDO*");
            }

            //carga el historial de visitas
            List<Document> seguimientos = (List<Document>) archivo.get("vis");
            // Recorrer el array "vis"
            if (seguimientos != null) {
                for (Document visita : seguimientos) {
                    // Obtener los campos de cada documento dentro del array "vis"
                    String fev = visita.getString("fev");
                    String com = visita.getString("com");
                    modelo.addRow(new Object[]{fev, com});
                }
            }
            /*  ESTE CODIGO ES BUENO solo PARA RECORRER OBJEROS EN UN CAMPO
            MongoCursor<Document> cursor = conexion.getIteradorByID(StrCodFila);
            try {
                while (cursor.hasNext()) {
                    Document documento = cursor.next();
                    Document visitas = (Document) documento.get("vis");
                    if (visitas != null) {
                        String fev = (String) visitas.get("fev");
                        String com = (String) visitas.get("com");
                        modelo.addRow(new Object[]{fev, com});
                    }
                }
            } catch (NullPointerException e) {
                // no hagas nada y coma callado xd
                JOptionPane.showMessageDialog(null, e, "Error:", JOptionPane.ERROR_MESSAGE);
            } finally {
                cursor.close();
            }
             */

 /*    Codigo Original....feo, antitecnico, pero creativo:
            Document seguimientos = (Document) archivo.get("vis"); //1

            if (seguimientos != null) {
                String[] Columna = new String[2];
                for (Map.Entry<String, Object> entry : seguimientos.entrySet()) { // 1 Funciona pero tedioso de implementar
                    if ("fev".equals(entry.getKey())) {
                        Columna[0] = (String) entry.getValue();
                    } else {
                        Columna[1] = (String) entry.getValue();
                        modelo.addRow(new Object[]{Columna[0], Columna[1]});
                    }
                }
            }
            } */
            // Asignar el modelo a la tabla
            JTableVisita.setModel(modelo);
        }
    }

    @Override
    public void dispose() {
        conexion.cierraSesion();
        //System.out.println("\t\t sesión cerrada");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableVisita;
    public javax.swing.JTextField TxtFec;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboEst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jLblEst;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexComen;
    // End of variables declaration//GEN-END:variables
}
